import {defaults,newTask,TYPES,validate,clone,FONT_OPTIONS,BUTTON_LABELS,BUTTON_EFFECTS} from '../game/model.js';
import {createGame,escapeHTML as esc} from '../game/game.js';
import {draft,projectBlob,readProject,download} from '../storage/storage.js';
import {migrate} from '../storage/schema.js';
import {optimize,prune} from '../media/media.js';
import {gameHTML,embedCode} from '../export/export.js';
import {shareCode} from '../export/share.js';
import {LIFT_DESIGNS} from '../game/lifts.js';
const $=s=>document.querySelector(s),localeNames={ru:'Русский',en:'English',de:'Deutsch',fr:'Français',es:'Español',it:'Italiano',pt:'Português',pl:'Polski',uk:'Українська',tr:'Türkçe',ar:'العربية',zh:'中文',ja:'日本語',ko:'한국어'};
const locales=Object.fromEntries(await Promise.all(Object.keys(localeNames).map(async code=>[code,await fetch(new URL('../locales/'+code+'.json',import.meta.url)).then(r=>r.json())])));
let buttonPreview='ready',selectedObject='',project=defaults(),tab='project',taskIndex=0,testing=false,history=[],future=[],saveTimer,toastTimer,saveQueue=Promise.resolve(),lastUpload=0;
const tabs=[['project','◈','Проект'],['layers','▱','Слои'],['frame','□','Рамка сцены'],['title','▤','Титульный лист'],['elevator','↟','Лифт и здание'],['player','♙','Персонаж'],['floors','▦','Этажи и пульт'],['tasks','☷','Задания'],['style','◐','Стиль заданий'],['buttons','▣','Кнопки'],['display','▥','Табло'],['rules','♡','Жизни и таймер'],['results','✧','Победа / поражение'],['language','◎','Язык'],['sound','♫','Звуки и анимации'],['export','↗','Экспорт / Genially']];
const game=createGame($('#game'),project,locales,{editor:true,onSelect:key=>{selectedObject=key;if(key==='enter')buttonPreview='enter';tab=tab==='layers'?'layers':({enter:'buttons',elevator:'elevator',display:'display',player:'player',floors:'floors',start:'floors',goal:'floors',hud:'rules'})[key]||tab;renderSettings();},onMove:(key,x,y)=>{record();project.layout[key].x=x;project.layout[key].y=y;selectedObject=key;refresh({settings:true});}});
function get(path){return path.split('.').reduce((o,k)=>o?.[k],project);}function set(path,value){const keys=path.split('.'),k=keys.pop();keys.reduce((o,k)=>o[k],project)[k]=value;}
const sizes=n=>n<1024?`${n} Б`:n<1024*1024?`${(n/1024).toFixed(1)} КБ`:`${(n/1024/1024).toFixed(2)} МБ`;
function field(label,path,type='text',extra=''){const value=get(path);return `<label class="field"><span>${label}${type==='range'?`<output>${value}</output>`:''}</span>${type==='textarea'?`<textarea data-path="${path}" ${extra}>${esc(value)}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(value)}" ${extra}>`}</label>`;}
function select(label,path,options){return `<label class="field"><span>${label}</span><select data-path="${path}">${Object.entries(options).map(([v,n])=>`<option value="${v}" ${String(get(path))===v?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;}
function check(label,path){return `<label class="check-field"><input type="checkbox" data-path="${path}" ${get(path)?'checked':''}>${label}</label>`;}
function range(label,path,min,max,step=1){return field(label,path,'range',`min="${min}" max="${max}" step="${step}"`);}
function two(a,b){return `<div class="two-col">${a}${b}</div>`;}
function media(label,path,kind='character'){const a=project.assets.find(x=>x.id===get(path));return `<div class="media-box"><label class="field"><span>${label}</span><input type="file" data-media="${path}" data-kind="${kind}" accept="image/png,image/jpeg,image/webp,image/gif"></label>${a?`<img class="media-thumb" src="${a.data}" alt="${esc(a.name)}"><span class="media-info">${esc(a.name)} · ${sizes(a.original)} → ${sizes(a.size)}</span><button data-remove-media="${path}">Удалить изображение</button>`:'<span class="media-info">PNG, JPG, WebP или GIF · сжатие автоматически</span>'}</div>`;}
function heading(title,desc=''){return `<h2>${title}</h2>${desc?`<p class="section-description">${desc}</p>`:''}`;}
function renderSettings(){
 $('#tabs').innerHTML=tabs.map(([key,icon,title])=>`<button data-tab="${key}" class="${tab===key?'active':''}" aria-current="${tab===key?'page':'false'}"><span class="tab-icon">${icon}</span>${title}</button>`).join('');let html='';
 if(tab==='layers')html=heading('Слои','Верхний пункт — передний план. Выберите объект, чтобы изменить его положение и масштаб.')+`<div class="layer-list">${Object.entries(project.layers).sort((a,b)=>b[1]-a[1]).map(([key],i,all)=>`<div class="layer-row"><button data-layer="${key}" class="${selectedObject===key?'active':''}">${({enter:'Кнопка «Войти в лифт»',elevator:'Лифт',player:'Персонаж',floors:'Пульт этажей',start:'Кнопка «Старт»',goal:'Цель',display:'Табло',hud:'Индикаторы'})[key]}</button><button data-layer-order="${key}" data-delta="1" aria-label="На слой выше" ${i===0?'disabled':''}>↑</button><button data-layer-order="${key}" data-delta="-1" aria-label="На слой ниже" ${i===all.length-1?'disabled':''}>↓</button></div>`).join('')}</div>`;
 if(tab==='frame')html=heading('Рамка сцены','Оформление прямоугольника, в котором расположены все объекты.')+select('Линия','sceneFrame.style',{none:'Без линии',solid:'Сплошная',dashed:'Пунктирная',dotted:'Точечная',double:'Двойная'})+range('Толщина линии, px','sceneFrame.width',0,20)+field('Цвет линии','sceneFrame.color','color')+range('Скругление, px','sceneFrame.radius',0,60)+range('Свечение, px','sceneFrame.glow',0,60)+field('Цвет свечения','sceneFrame.glowColor','color');
 if(tab==='project')html=heading('Начнём с идеи','Дайте игре название. Остальное — дело вашей фантазии.')+field('Название игры','project.title')+field('Автор','project.author')+select('Язык игры','project.locale',localeNames)+select('Базовое разрешение','project.width',{'1200':'1200 × 675','1600':'1600 × 900','1920':'1920 × 1080'})+`<div class="note">✦ ${project.project.width} × ${project.project.height} · 16:9<br>Сцена автоматически подстраивается под экран.</div>`+check('Сохранять черновик автоматически','project.autosave')+'<h3>Оптимизация медиа</h3>'+range('Качество изображений','project.quality',.1,1,.01)+range('Сжатие GIF с потерями · 0 = без потерь','project.gifLossy',0,100)+`<p class="help">GIF сохраняют анимацию. Обработка происходит на вашем устройстве.</p><button data-action="reset" class="full-width">Создать новую игру</button>`;
 if(tab==='title')html=heading('Первое впечатление','Пригласите ученика в маленькое приключение.')+check('Показывать титульный экран','screens.title.enabled')+field('Заголовок','screens.title.title')+field('Описание','screens.title.description','textarea')+field('Текст кнопки · пусто = перевод','screens.title.button')+two(field('Фон','screens.title.background','color'),field('Цвет текста','screens.title.color','color'))+range('Размер заголовка','screens.title.size',22,72)+media('Изображение или GIF','screens.title.media')+`<button data-action="title-preview" class="full-width">Посмотреть титульный экран</button>`;
 if(tab==='elevator')html=heading('Выберите свой лифт','Три готовых оформления. Цвета и фон можно изменить.')+`<div class="lift-designs">${Object.entries(LIFT_DESIGNS).map(([id,d])=>`<button data-design="${id}" class="${project.elevator.design===id?'active':''}" aria-pressed="${project.elevator.design===id}"><img src="public/lifts/${id}.svg" alt=""><span>${d.name}</span></button>`).join('')}</div>`+two(field('Однотонный фон','theme.background','color'),field('Подсветка','theme.accent','color'))+two(field('Корпус лифта','theme.frame','color'),field('Двери','theme.door','color'))+media('Своя картинка фона','theme.backgroundImage','background')+select('Заполнение картинки','theme.fit',{cover:'Заполнить',contain:'Вместить'})+range('Непрозрачность картинки, %','theme.imageOpacity',0,100)+range('Длительность движения, сек.','elevator.speed',.2,5,.1)+range('Открытие дверей, сек.','elevator.doorSpeed',.1,3,.1);
 if(tab==='player')html=heading('Ваш спутник','Загрузите своего героя или оставьте нашего робота.')+media('Персонаж','player.media')+range('Размер персонажа','player.scale',.2,3,.1)+range('Положение по горизонтали, %','layout.player.x',2,98)+range('Положение по вертикали, %','layout.player.y',2,98)+check('Отразить по горизонтали','player.flip')+check('Анимация входа','player.animate')+check('Анимация ожидания','player.idle');
 if(tab==='floors')html=heading('Цель путешествия','Ученик выбирает этаж внутри кабины. Неверный ответ отнимает одну жизнь. Если жизни остались, ученик переходит к следующему вопросу без повтора. Достигнув цели с оставшейся жизнью, ученик побеждает.')+`<div class="note">Сейчас в игре: <b>${project.tasks.length} этажей</b>.<br>Добавляйте и удаляйте их в разделе «Задания».</div>`+field('Формулировка цели · пусто = перевод','floors.goalText')+`<p class="help">Можно использовать {floor} — номер выбранного этажа. Например: «Доберись до этажа {floor}».</p>`+select('Режим цели','floors.mode',{fixed:'Заданный этаж',free:'Свободный выбор ученика'})+select('Целевой этаж','floors.target',Object.fromEntries([['0','Верхний (автоматически)'],...project.tasks.map((_,i)=>[String(i+1),'Этаж '+(i+project.floors.start)])]))+select('Начало нумерации','floors.start',{'1':'С первого этажа','0':'С нулевого этажа'})+range('Колонки пульта','floors.columns',1,5)+range('Размер кнопок, px','floors.size',32,72)+check('Круглые кнопки','floors.round')+field('Цвет целевого этажа','theme.accent','color');
 if(tab==='tasks'){html=heading('Маршрут к знаниям','Пять способов превратить вопрос в открытие.')+`<div class="add-task"><select id="new-task-type" aria-label="Тип нового задания">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button data-action="add-task" aria-label="Добавить задание">＋</button></div><div class="task-list">${project.tasks.map((t,i)=>`<div class="task-row ${i===taskIndex?'active':''}" tabindex="0" role="button" data-task-index="${i}" aria-label="Редактировать этаж ${i+project.floors.start}"><header><b>${String(i+project.floors.start).padStart(2,'0')}</b><span>${TYPES[t.type]}</span></header><p>${esc(t.prompt||'Без вопроса')}</p></div>`).join('')}</div>`;const q=project.tasks[taskIndex];if(q){const path='tasks.'+taskIndex;html+=`<h3>Этаж ${taskIndex+project.floors.start} · ${TYPES[q.type]}</h3><div class="task-actions"><button data-action="task-up" ${taskIndex===0?'disabled':''} aria-label="Переместить задание выше">↑</button><button data-action="task-down" ${taskIndex===project.tasks.length-1?'disabled':''} aria-label="Переместить задание ниже">↓</button><button data-action="duplicate-task">Дублировать</button><button data-action="delete-task" class="danger">Удалить</button></div>`+field('Формулировка',path+'.prompt','textarea')+`<div class="note">Формулы LaTeX: <code>$x^2$</code> в строке, <code>$$\\frac{a}{b}$$</code> отдельно. Поддерживаются корни, дроби, степени и системы уравнений.</div><button data-action="sample-task" class="full-width">Посмотреть задание и формулы</button>`;
 if(['single','multiple','order'].includes(q.type)){html+=`<p class="help">${q.type==='order'?'Введите карточки в правильном порядке. В игре они будут перемешаны.':'Отметьте правильный ответ'+(q.type==='multiple'?' (можно несколько).':'.')}</p>`+q.answers.map((a,i)=>`<div class="answer-editor">${q.type==='order'?`<span>${i+1}.</span>`:`<input type="${q.type==='single'?'radio':'checkbox'}" name="correct-answer" data-correct="${i}" ${q.correct.includes(i)?'checked':''} aria-label="Верный вариант ${i+1}">`}<input type="text" data-path="${path}.answers.${i}" value="${esc(a)}" aria-label="Вариант ${i+1}"><button data-delete-answer="${i}" aria-label="Удалить вариант ${i+1}" ${q.answers.length<=2?'disabled':''}>×</button></div>`).join('')+`<button data-action="add-answer" class="full-width" ${q.answers.length>=(q.type==='single'?8:10)?'disabled':''}>＋ Добавить вариант</button>`;if(q.type!=='order')html+=check('Перемешивать варианты',path+'.shuffle');}
 if(q.type==='text')html+=`<label class="field"><span>Допустимые ответы · каждый с новой строки</span><textarea data-accepted>${esc(q.accepted.join('\n'))}</textarea></label>`+check('Не учитывать регистр',path+'.ignoreCase')+check('Не учитывать пробелы',path+'.ignoreSpaces')+check('Считать ё и е одинаковыми',path+'.yo')+check('Числовой ответ',path+'.numeric')+(q.numeric?field('Числовой допуск',path+'.tolerance','number','min="0" step="0.01"'):'');
 if(q.type==='oral')html+=field('Образец / критерии ответа',path+'.sample','textarea')+select('Кто проверяет','tasks.'+taskIndex+'.oralMode',{self:'Ученик — самопроверка',teacher:'Преподаватель'});
 html+=media('Иллюстрация к вопросу',path+'.media','task')+field('Вес задания в бонусах',path+'.points','number','min="0" max="100"')+field('Сообщение при верном ответе',path+'.onCorrect')+field('Сообщение при ошибке',path+'.onWrong');}}
 if(tab==='buttons')html=heading('Кнопки','У каждой кнопки свои цвета и свечение.')+Object.entries(BUTTON_LABELS).map(([key,label])=>'<h3>'+label+'</h3>'+two(field('Фон','buttons.'+key+'.background','color'),field('Цвет букв','buttons.'+key+'.color','color'))+field('Цвет свечения','buttons.'+key+'.glowColor','color')+range('Свечение, px','buttons.'+key+'.glow',0,60)+range('Размер кнопки','buttons.'+key+'.scale',.5,2,.05)+select('Эффект при наведении','buttons.'+key+'.effect',BUTTON_EFFECTS)+`<button data-button-preview="${key}" class="full-width">Посмотреть кнопку «${label}»</button>`).join('');
 if(tab==='display')html=heading('Табло лифта','Фон, горящие цифры и их свечение.')+two(field('Фон табло','displayStyle.background','color'),field('Цвет цифр','displayStyle.color','color'))+select('Дизайн цифр','displayStyle.digits',{classic:'Классические',neon:'Неоновые',segments:'Электронные · 7 сегментов'})+field('Цвет свечения','displayStyle.glowColor','color')+range('Свечение, px','displayStyle.glow',0,60);
 if(tab==='style')html=heading('Всё в вашем стиле','Оформление вопросов и игровых кнопок.')+two(field('Цвет окна','theme.panel','color'),field('Цвет сообщений','theme.text','color'))+select('Шрифт','theme.font',FONT_OPTIONS)+`<p class="help">Шрифт применяется ко всей игре. Если его нет на устройстве ученика, браузер использует замену.</p>`+range('Размер вопроса, px','theme.fontSize',12,60)+range('Размер ответов, px','theme.answerFontSize',12,48)+two(field('Цвет вопроса','theme.questionColor','color'),field('Цвет ответов','theme.answerColor','color'))+field('Фон вариантов ответа','theme.answerBackground','color')+check('Полужирный заголовок','theme.bold')+range('Межстрочный интервал','theme.lineHeight',1,2.5,.1)+select('Выравнивание текста','theme.align',{left:'Слева',center:'По центру',right:'Справа'})+range('Ширина окна, %','theme.taskWidth',40,95)+range('Скругление окна','theme.radius',0,60)+range('Отступы','theme.padding',0,60)+range('Тень','theme.shadow',0,80)+range('Непрозрачность окна, %','theme.opacity',10,100)+field('Цвет рамки','theme.border','color')+two(field('Фон кнопки «Проверить»','buttons.check.background','color'),field('Буквы кнопки «Проверить»','buttons.check.color','color'))+range('Скругление кнопок','theme.buttonRadius',0,50)+`<button data-action="sample-task" class="full-width">Посмотреть окно задания</button>`;
 if(tab==='rules')html=heading('Правила путешествия','Настройте сложность под своих учеников.')+range('Количество жизней','rules.lives',1,10)+select('Иконка жизни','rules.lifeIcon',{'♥':'Сердце ♥','▰':'Батарея ▰','★':'Звезда ★'})+media('Своя иконка жизни','rules.lifeMedia')+check('Бонусная жизнь за правильный ответ','rules.bonusLife')+'<h3>Таймер</h3>'+select('Режим','rules.timer.mode',{off:'Отключён',game:'На всю игру',task:'На каждое задание'})+(project.rules.timer.mode!=='off'?field('Время, секунд','rules.timer.seconds','number','min="1" max="86400"')+check('Поражение, когда время истекло','rules.timer.mandatory')+field('Предупреждение за N секунд','rules.timer.warning','number','min="0" max="86400"'):'')+'<h3>Бонусы</h3>'+check('Показывать бонусы','rules.bonus.enabled')+(project.rules.bonus.enabled?field('Название счётчика · пусто = перевод','rules.bonus.label')+field('За верный ответ','rules.bonus.base','number','min="0" max="100"')+field('За ответ без ошибки','rules.bonus.perfect','number','min="0" max="100"')+two(field('Серия ответов · 0 = выкл.','rules.bonus.streak','number','min="0" max="100"'),field('Бонус за серию','rules.bonus.streakPoints','number','min="0" max="100"'))+two(field('Быстрее N секунд · 0 = выкл.','rules.bonus.fast','number','min="0" max="3600"'),field('Бонус за скорость','rules.bonus.fastPoints','number','min="0" max="100"')):'')+'<h3>Обратная связь</h3>'+field('Верный ответ · пусто = перевод','rules.correct')+field('Неверный ответ · пусто = перевод','rules.wrong');
 if(tab==='results')html=heading('Финал приключения','Поддержите ученика при любом результате.')+['win','lose'].map(k=>'<h3>'+(k==='win'?'Победа':'Поражение')+'</h3>'+field('Заголовок',`screens.${k}.title`)+field('Описание',`screens.${k}.description`,'textarea')+field('Цвет фона',`screens.${k}.background`,'color')+media('Изображение или GIF',`screens.${k}.media`)+check('Свечение',`screens.${k}.glow`)+check('Показывать статистику',`screens.${k}.stats`)+`<button data-screen="${k}" class="full-width">Предпросмотр ${k==='win'?'победы':'поражения'}</button>`).join('');
 if(tab==='language')html=heading('Без языковых границ','Меняются системные подписи. Ваши вопросы остаются на языке оригинала.')+select('Язык игры','project.locale',localeNames)+select('Базовый язык для пропущенных переводов','project.fallback',{ru:'Русский',en:'English'})+`<div class="locale-labels">${Object.entries(locales[project.project.locale]||locales.ru).map(([k,v])=>`<div><small>${esc(locales.ru[k])}</small>${esc(v)}</div>`).join('')}</div>`;
 if(tab==='sound')html=heading('Чуть больше магии','Деликатные звуки и плавное движение.')+check('Включить звуки','elevator.sounds')+range('Громкость','elevator.volume',0,1,.05)+check('Звук правильного ответа','elevator.successSound')+check('Звук ошибки','elevator.errorSound')+check('Звук прибытия лифта','elevator.arrivalSound')+check('Открытие и закрытие дверей','elevator.doorSound')+check('Звук движения','elevator.travelSound')+`<div class="sound-previews">${[['door','Двери'],['travel','Движение'],['arrival','Прибытие'],['success','Верно'],['error','Ошибка']].map(([key,title])=>`<button data-sound="${key}">▶ ${title}</button>`).join('')}</div>`+check('Анимации и подсветка','elevator.motion')+`<div class="note">Системная настройка «Уменьшение движения» учитывается автоматически. Звук включается после первого действия в игре.</div>`;
 if(tab==='export')html=heading('Готовый код для Genially','Игра автоматически упаковывается в iframe. Отдельно публиковать каждый файл не нужно.')+`<button data-action="embed" class="full-width primary">〈/〉 Получить готовый код</button><p></p><button data-action="light" class="full-width">✧ Облегчить код для Genially</button><div class="note">Вставьте скопированный код через «Вставка → Другие» в Genially. Ссылка содержит именно текущую игру: задания, оформление и медиа. Обновления редактора не меняют игру по этому коду.</div><button data-action="html" class="full-width">↓ Скачать автономный HTML</button><h3>Свой опубликованный файл (необязательно)</h3>`+field('HTTPS-адрес игры','project.url','url','placeholder="https://…/my-game.html"')+`<p class="help">Для проектов с очень большими медиа можно опубликовать HTML отдельно и получить короткий iframe на него.</p><button data-action="save" class="full-width">Сохранить проект</button><div class="note">${project.tasks.length} заданий · ${project.assets.length} медиа<br>Медиа в проекте: ${sizes(project.assets.reduce((n,a)=>n+a.size,0))}</div>`;
 if(selectedObject&&project.layout[selectedObject])html=`<section class="placement-settings"><h3>Расположение выделенного объекта</h3><p class="help">Перетаскивайте зелёную пунктирную рамку в сцене. С клавиатуры: стрелки, Shift + стрелки — крупный шаг.</p>${range('По горизонтали, %','layout.'+selectedObject+'.x',2,98,.1)}${range('По вертикали, %','layout.'+selectedObject+'.y',2,98,.1)}${range('Масштаб','layout.'+selectedObject+'.scale',.3,2,.05)}<button data-action="reset-position" class="full-width">Вернуть исходное положение</button></section>`+html;
 $('#settings').innerHTML=html;syncSelectionTools();
}
function syncSelectionTools(){const pos=project.layout[selectedObject],bar=$('#selection-tools');bar.hidden=testing||!pos;if(!pos)return;$('#selection-name').textContent=({enter:'Кнопка «Войти в лифт»',elevator:'Лифт',player:'Персонаж',floors:'Пульт этажей',start:'Кнопка «Старт»',goal:'Цель',display:'Табло',hud:'Индикаторы'})[selectedObject];$('#selection-scale').value=pos.scale;$('#selection-scale-value').textContent=Math.round(pos.scale*100)+'%';}
$('#selection-scale').addEventListener('input',e=>{if(testing||!project.layout[selectedObject])return;record();project.layout[selectedObject].scale=Number(e.target.value);refresh();const el=$('#settings [data-path="layout.'+selectedObject+'.scale"]');if(el){el.value=e.target.value;el.closest('label').querySelector('output').textContent=e.target.value;}});
function record(){history.push(clone(project));if(history.length>60)history.shift();future=[];}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function autosave(){clearTimeout(saveTimer);if(!project.project.autosave){$('#save-status').textContent='Автосохранение выключено';return;}$('#save-status').textContent='Сохраняем…';saveTimer=setTimeout(()=>{const snapshot=clone(project);saveQueue=saveQueue.catch(()=>{}).then(()=>draft('put',snapshot)).then(()=>{$('#save-status').textContent='● Черновик сохранён';}).catch(()=>{$('#save-status').textContent='Не удалось сохранить черновик';toast('Недостаточно места или браузер запрещает хранение. Сохраните проект в файл.');});},500);}
function previewButton(key){buttonPreview=key;if(key==='begin')game.showScreen('title');else if(key==='check')game.showTask(taskIndex);else{const view=key==='enter'?'lobby':'cabin';game.setView(view);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));}}
function refresh({settings=false,save=true}={}){if(testing){testing=false;game.setEditor(true);syncMode();}game.update(project);if(tab==='style'||tab==='tasks')game.showTask(taskIndex);if(tab==='buttons')previewButton(buttonPreview);if(tab==='title')game.showScreen('title');$('#project-heading').textContent=project.project.title||'Новая игра';$('#task-count').textContent=project.tasks.length;$('.dimensions').textContent=`${project.project.width} × ${project.project.height} · 16:9`;document.querySelector('[data-action="undo"]').disabled=!history.length;document.querySelector('[data-action="redo"]').disabled=!future.length;if(settings)renderSettings();syncSelectionTools();if(save)autosave();}
function syncMode(){syncSelectionTools();$('#edit-mode').classList.toggle('active',!testing);$('#test-mode').classList.toggle('active',testing);$('.preview-wrap').classList.toggle('testing',testing);$('#preview-hint').textContent=testing?'Пройдите игру как ученик. «Редактор» вернёт вас к настройкам.':'Выделите объект и перетащите зелёную рамку. Стрелки — точное перемещение.';}
function dialog(html){$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
function close(){$('#dialog').close();}
function confirmDialog(title,body,yes){return new Promise(resolve=>{dialog(`<h2>${esc(title)}</h2><p>${esc(body)}</p><div class="dialog-buttons"><button id="cancel">Отмена</button><button id="confirm" class="primary">${esc(yes)}</button></div>`);$('#cancel').onclick=()=>{close();resolve(false);};$('#confirm').onclick=()=>{close();resolve(true);};$('#dialog').addEventListener('cancel',()=>resolve(false),{once:true});});}
function errors(){const e=validate(project);if(!e.length)return false;dialog(`<h2>Проверьте задания</h2><ul>${e.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="dialog-buttons"><button data-action="close">Понятно</button></div>`);return true;}
async function embed(light=false){
 if(errors())return;
 dialog(`<h2>${light?'Облегчить код для Genially':'Готовый код для Genially'}</h2><p id="embed-status">${light?'Сжимаем данные игры…':'Формируем код вашей игры…'}</p><textarea id="embed-output" class="code-output" aria-label="Готовый код для Genially" readonly></textarea><p id="embed-size" class="help"></p><p id="embed-error" class="error-text"></p><p class="help">В Genially откройте «Вставка → Другие», вставьте весь код и нажмите «Вставить». Игра закреплена за своей версией. Чтобы обновить уже готовую игру, замените её код iframe.</p><a id="open-shared" target="_blank" rel="noopener" hidden>Открыть эту игру в браузере ↗</a><details><summary>Использовать свой опубликованный HTML</summary><label class="field"><span>Адрес HTML-файла (необязательно)</span><input id="embed-url" type="url" value="${esc(project.project.url)}" placeholder="https://…/game.html"></label><button id="use-custom-url">Сформировать iframe на этот файл</button></details><div class="dialog-buttons"><button data-action="close">Закрыть</button><button id="download-embed">Скачать код</button><button id="copy-embed" class="primary" disabled>Копировать код</button></div>`);
 const box=$('#embed-output'),copy=$('#copy-embed'),size=$('#embed-size'),status=$('#embed-status'),error=$('#embed-error'),link=$('#open-shared');
 function show(code,url){box.value=code;copy.disabled=false;link.href=url;link.hidden=false;}
 copy.onclick=async()=>{try{await navigator.clipboard.writeText(box.value);toast('Код скопирован — вставьте его в Genially');}catch{box.focus();box.select();error.textContent='Браузер не разрешил доступ к буферу. Код выделен: нажмите Ctrl/Cmd+C.';}};
 $('#download-embed').onclick=()=>download(new Blob([box.value],{type:'text/plain'}),'genially-embed.txt');
 $('#use-custom-url').onclick=()=>{try{const url=$('#embed-url').value.trim(),code=embedCode(url,project.project.title);record();project.project.url=url;autosave();show(code,url);status.textContent='Готовый iframe на опубликованную игру';size.textContent=sizes(new Blob([code]).size);error.textContent='';}catch(e){error.textContent=e.message;}};
 try{const normal=await shareCode(project,{compact:false}),result=light?await shareCode(project,{compact:true}):normal;show(result.code,result.url);status.textContent='Код готов. Скопируйте его целиком в Genially.';size.textContent=light?`До: ${sizes(normal.bytes)} · После: ${sizes(result.bytes)} · Экономия: ${Math.max(0,(1-result.bytes/normal.bytes)*100).toFixed(1)}%`:sizes(result.bytes);if(result.large)error.textContent='В коде много медиа. Если Genially отклоняет длинный код, скачайте HTML, опубликуйте его и используйте собственный адрес ниже.';}catch(e){error.textContent=e.message;status.textContent='Не удалось сформировать код';}
}
const actions={
 'selected-layers'(){tab='layers';renderSettings();},
 tasks(){tab='tasks';renderSettings();},close,
 edit(){testing=false;game.setEditor(true);syncMode();},
 test(){if(errors())return;testing=true;game.setEditor(false);syncMode();},
 async save(){try{download(projectBlob(project),(project.project.title||'game')+'.liftproject');toast('Проект сохранён в файл');}catch(e){toast(e.message);}},
 load(){$('#project-file').click();},
 async html(){if(errors())return;try{download(new Blob([await gameHTML(project,locales)],{type:'text/html'}),'lift-game.html');toast('Автономная игра сохранена');}catch(e){toast(e.message);}},
 async light(){await embed(true);},embed:()=>embed(false),
 'reset-position'(){if(!selectedObject)return;record();project.layout[selectedObject]=clone(defaults().layout[selectedObject]);refresh({settings:true});},
 undo(){if(!history.length)return;future.push(clone(project));project=history.pop();taskIndex=Math.min(taskIndex,project.tasks.length-1);refresh({settings:true});},
 redo(){if(!future.length)return;history.push(clone(project));project=future.pop();refresh({settings:true});},
 async reset(){if(!await confirmDialog('Создать новую игру?','Текущий черновик будет заменён. Сохраните проект в файл, если хотите вернуться к нему.','Создать'))return;record();lastUpload++;project=defaults();taskIndex=0;tab='project';refresh({settings:true});},
 'add-task'(){if(project.tasks.length>=100){toast('Максимум 100 заданий');return;}record();project.tasks.push(newTask($('#new-task-type').value));taskIndex=project.tasks.length-1;refresh({settings:true});},
 'duplicate-task'(){if(project.tasks.length>=100)return;record();const q=clone(project.tasks[taskIndex]);q.id='id-'+crypto.randomUUID();project.tasks.splice(taskIndex+1,0,q);taskIndex++;refresh({settings:true});},
 async 'delete-task'(){if(!await confirmDialog('Удалить задание?','Нумерация этажей будет пересчитана. Неиспользуемая иллюстрация также будет удалена.','Удалить'))return;record();project.tasks.splice(taskIndex,1);project.floors.target=Math.min(project.floors.target,project.tasks.length);taskIndex=Math.max(0,Math.min(taskIndex,project.tasks.length-1));lastUpload++;prune(project);refresh({settings:true});},
 'task-up'(){moveTask(-1);},'task-down'(){moveTask(1);},
 'add-answer'(){const q=project.tasks[taskIndex];if(q.answers.length>=(q.type==='single'?8:10))return;record();q.answers.push('Новый вариант');refresh({settings:true});},
 'title-preview'(){actions.edit();game.showScreen('title');},
 'sample-task'(){actions.edit();game.showTask(taskIndex);}
};
function moveTask(delta){const target=taskIndex+delta;if(target<0||target>=project.tasks.length)return;record();[project.tasks[taskIndex],project.tasks[target]]=[project.tasks[target],project.tasks[taskIndex]];taskIndex=target;lastUpload++;refresh({settings:true});}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-task-index]');if(!b)return;try{if(b.dataset.buttonPreview){if(testing)actions.edit();previewButton(b.dataset.buttonPreview);return;}if(b.dataset.layer){selectedObject=b.dataset.layer;if(selectedObject==='enter'){game.setView('lobby');document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view==='lobby'));}game.selectObject(selectedObject);renderSettings();return;}if(b.dataset.layerOrder){record();const keys=Object.keys(project.layers).sort((a,b)=>project.layers[a]-project.layers[b]),i=keys.indexOf(b.dataset.layerOrder),j=i+Number(b.dataset.delta);if(j>=0&&j<keys.length)[keys[i],keys[j]]=[keys[j],keys[i]];keys.forEach((k,n)=>project.layers[k]=n+1);refresh({settings:true});return;}if(b.dataset.design){record();const d=LIFT_DESIGNS[b.dataset.design];project.elevator.design=b.dataset.design;project.theme.frame=d.frame;project.theme.door=d.door;project.theme.accent=d.accent;refresh({settings:true});return;}if(b.dataset.view){if(testing)actions.edit();game.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el===b));return;}if(b.dataset.sound){if(!await game.playSound(b.dataset.sound))toast('Увеличьте громкость и проверьте звук устройства.');return;}if(b.dataset.tab){tab=b.dataset.tab;selectedObject='';renderSettings();if(!testing){if(tab==='style'||tab==='tasks')game.showTask(taskIndex);else if(tab==='buttons'){game.update(project);previewButton(buttonPreview);}else if(tab==='title')game.showScreen('title');else game.update(project);}return;}if(b.dataset.taskIndex!==undefined){taskIndex=Number(b.dataset.taskIndex);renderSettings();if(!testing)game.showTask(taskIndex);return;}if(b.dataset.screen){actions.edit();game.showScreen(b.dataset.screen);return;}if(b.dataset.removeMedia){if(await confirmDialog('Удалить изображение?','Изображение будет убрано из этого элемента.','Удалить')){record();set(b.dataset.removeMedia,'');prune(project);refresh({settings:true});}return;}if(b.dataset.deleteAnswer!==undefined){const q=project.tasks[taskIndex],n=Number(b.dataset.deleteAnswer);if(q.answers.length<=2)return;record();q.answers.splice(n,1);q.correct=q.correct.filter(i=>i!==n).map(i=>i>n?i-1:i);refresh({settings:true});return;}if(b.dataset.action&&actions[b.dataset.action])await actions[b.dataset.action]();}catch(err){toast(err.message||'Не удалось выполнить действие');}});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.path){let value=el.type==='checkbox'?el.checked:['range','number'].includes(el.type)?Number(el.value):el.value;if(el.type==='number'&&(!el.value||!el.checkValidity()))return;if(['floors.target','floors.start','project.width'].includes(el.dataset.path))value=Number(value);record();set(el.dataset.path,value);if(el.dataset.path.startsWith('buttons.'))buttonPreview=el.dataset.path.split('.')[1];if(el.dataset.path==='project.width')project.project.height=value*9/16;if(el.type==='range')el.closest('label').querySelector('output').textContent=value;refresh();if(el.tagName==='SELECT'||el.type==='checkbox')renderSettings();if(tab==='title'&&el.dataset.path.startsWith('screens.title.'))game.showScreen('title');}if(el.hasAttribute('data-accepted')){record();project.tasks[taskIndex].accepted=el.value.split('\n');refresh();}if(el.dataset.correct!==undefined){record();const q=project.tasks[taskIndex],i=Number(el.dataset.correct);q.correct=q.type==='single'?[i]:el.checked?[...q.correct,i]:q.correct.filter(x=>x!==i);refresh();}});
document.addEventListener('change',async e=>{const el=e.target;if(!el.dataset.media||!el.files[0])return;const path=el.dataset.media,file=el.files[0],epoch=lastUpload,taskId=path.startsWith('tasks.')?project.tasks[taskIndex]?.id:null;el.disabled=true;toast('Оптимизируем изображение…');try{const a=await optimize(file,el.dataset.kind,project);if(epoch!==lastUpload||(taskId&&get(path.split('.').slice(0,2).join('.')+'.id')!==taskId)){toast('Проект изменился. Загрузите изображение ещё раз.');return;}record();project.assets.push(a);set(path,a.id);prune(project);refresh({settings:true});toast(a.warning||`Медиа готово: ${sizes(a.original)} → ${sizes(a.size)}`);}catch(err){toast(err.message);}finally{el.disabled=false;el.value='';}});
$('#project-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const next=await readProject(f);if(!await confirmDialog('Открыть проект?','Настройки редактора будут заменены загруженным проектом.','Открыть'))return;record();lastUpload++;project=next;taskIndex=0;refresh({settings:true});toast('Проект загружен');}catch(err){toast('Не удалось открыть проект: '+err.message);}finally{e.target.value='';}};
document.addEventListener('keydown',e=>{if(e.target.matches('[data-task-index]')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input,textarea')&&!$('#dialog').open){e.preventDefault();e.shiftKey?actions.redo():actions.undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();actions.save();}});
refresh({settings:true,save:false});
try{const saved=await draft('get');if(saved){dialog(`<h2>Продолжим с того же этажа?</h2><p>На этом устройстве сохранён черновик «${esc(saved.project?.title||'Лифт')}».</p><div class="dialog-buttons"><button id="fresh">Начать заново</button><button id="restore" class="primary">Продолжить редактирование</button></div>`);const restore=()=>{try{project=migrate(saved);close();refresh({settings:true});toast('Черновик восстановлен');}catch(e){close();toast('Черновик повреждён. Загрузите сохранённый файл проекта.');}};$('#restore').onclick=restore;$('#fresh').onclick=async()=>{await draft('delete');close();refresh();};$('#dialog').addEventListener('cancel',e=>{e.preventDefault();restore();},{once:true});}else autosave();}catch{$('#save-status').textContent='Локальное хранение недоступно';}
