import {initialGame,submit,tick,checkAnswer} from './model.js';
export function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function createGame(root,project,dictionaries,{editor=false,onSelect=()=>{}}={}){
 let p=project,s=initialGame(p),selected=[],order=[],sample=false,feedback='',transition=0,disposed=false,audio;
 const esc=escapeHTML,t=k=>dictionaries[p.project.locale]?.[k]||dictionaries[p.project.fallback]?.[k]||dictionaries.ru?.[k]||k;
 const asset=id=>p.assets.find(a=>a.id===id)?.data||'';
 const img=(id,cls='')=>asset(id)?`<img class="${cls}" src="${asset(id)}" alt="">`:'';
 const time=n=>Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toString().padStart(2,'0');
 const motion=()=>p.elevator.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
 function sound(kind){if(!p.elevator.sounds||!p.elevator[kind+'Sound'])return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=kind==='error'?180:kind==='arrival'?660:880;g.gain.value=p.elevator.volume*.15;g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.24);o.start();o.stop(audio.currentTime+.24);}catch{}}
 function defer(fn,seconds){clearTimeout(transition);transition=setTimeout(()=>{if(!disposed)fn();},motion()?seconds*1000:20);}
 function applyStyle(){const v={'accent':p.theme.accent,'bg':p.theme.background,'ink':p.theme.text,'panel':p.theme.panel,'door':p.theme.door,'frame':p.theme.frame,'radius':p.theme.radius+'px','font':p.theme.font,'task-size':p.theme.fontSize+'px','border':p.theme.border,'shadow':p.theme.shadow+'px','opacity':p.theme.opacity/100,'task-width':p.theme.taskWidth+'%','pad':p.theme.padding+'px','button-radius':p.theme.buttonRadius+'px','button-color':p.theme.buttonColor,'button-text':p.theme.buttonText,'line-height':p.theme.lineHeight,'align':p.theme.align,'weight':p.theme.bold?'700':'400','hero-scale':p.player.scale,'hero-x':p.player.x+'%','hero-y':p.player.y+'%','hero-flip':p.player.flip?-1:1,'door-speed':p.elevator.doorSpeed+'s','cols':p.floors.columns,'floor-size':p.floors.size+'px','floor-radius':p.floors.round?'50%':'10px'};for(const[k,value]of Object.entries(v))root.style.setProperty('--'+k,value);root.dir=p.project.locale==='ar'?'rtl':'ltr';root.className='game '+(motion()?'':'still ')+(editor?'editing ':'')+s.phase;}
 const robot=`<div class="robot"><div class="antenna"></div><div class="robot-head"><div class="robot-face"><i></i><i></i><b></b></div></div><div class="robot-body"><span>✦</span></div><div class="robot-arm left"></div><div class="robot-arm right"></div><div class="robot-foot left"></div><div class="robot-foot right"></div></div>`;
 function scene(){const shown=editor?0:s.floor;return `<div class="scene ${p.elevator.lines?'floor-lines':''} ${p.theme.gradient?'gradient':''}">${asset(p.theme.backgroundImage)?`<img class="scene-bg" src="${asset(p.theme.backgroundImage)}" style="object-fit:${p.theme.fit==='contain'?'contain':'cover'};opacity:${p.theme.imageOpacity/100}" alt="">`:''}<div class="architecture arch-one"></div><div class="architecture arch-two"></div><div class="scene-heading"><small>✦ ${esc(p.project.title)}</small><h2>${esc(t('goal'))} <span>${p.tasks.length?((editor?(p.floors.target||p.tasks.length):s.target)+p.floors.start-1):'—'}</span></h2></div><div class="plant"><i></i><i></i><i></i><b></b></div><div class="lift" data-select="elevator"><div class="lift-sign ${p.elevator.display==='plain'?'plain':''}"><span>${p.elevator.direction==='up'?'↑':'↓'}</span> ${String(shown+p.floors.start-1).padStart(2,'0')}</div><div class="lift-frame"><div class="lift-interior"><div class="interior-light"></div><div class="rail"></div></div><div class="lift-door door-left"></div><div class="lift-door door-right"></div><div class="door-seam"></div></div><div class="lift-step"></div></div><div class="hero ${p.player.animate?'animate':''} ${p.player.idle?'idle':''}" data-select="player">${asset(p.player.media)?img(p.player.media):robot}</div><div class="floor-console" data-select="floors"><div class="console-label">${esc(t('floor'))} <span>↑</span></div><div class="floor-grid">${p.tasks.map((_,i)=>`<button data-floor="${i+1}" class="floor-button ${i<shown?'passed':''} ${i+1==s.target?'target':''}" ${!editor&&(s.phase!=='lobby'||(p.floors.mode==='fixed'&&i+1!==s.target))?'disabled':''} aria-label="${esc(t('floor'))} ${i+p.floors.start}">${i+p.floors.start}</button>`).reverse().join('')}</div><div class="console-line"></div><small>${esc(t('progress'))} <b>${shown} / ${p.tasks.length}</b></small></div><div class="floor-ground"></div><div class="scene-caption">${esc(editor?t('choose'):s.phase==='lobby'?t('choose'):s.phase==='boarding'?t('enter'):s.phase==='moving'?(feedback||t('correct')):'')}</div></div>`;}
 function hud(){return `<div class="game-hud"><span class="hud-pill">${p.rules.lifeMedia?img(p.rules.lifeMedia,'life-icon'):esc(p.rules.lifeIcon)} <b>${editor?p.rules.lives:s.lives}</b><small>${esc(t('lives'))}</small></span>${p.rules.timer.mode!=='off'?`<span class="hud-pill timer ${s.remaining<=p.rules.timer.warning?'warning':''}">◷ <b data-time>${time(editor?p.rules.timer.seconds:s.remaining)}</b><small>${esc(t('time'))}</small></span>`:''}${p.rules.bonus.enabled?`<span class="hud-pill bonus">✦ <b>${Math.round(s.bonus*100)/100}</b><small>${esc(p.rules.bonus.label||t('bonus'))}</small></span>`:''}</div>`;}
 function screen(kind){const c=p.screens[kind];const title=kind==='title'?c.title:c.title;return `<div class="screen-overlay" style="background:${c.background}ee"><section class="screen-card ${c.glow?'glow':''}" style="${kind==='title'?`color:${c.color};--screen-title:${c.size}px`:''}" role="dialog" aria-label="${esc(title)}">${img(c.media,'screen-media')}<div class="screen-emblem">${kind==='title'?'↑':kind==='win'?'✦':'↻'}</div><h1>${esc(title)}</h1><p>${esc(c.description)}</p>${kind!=='title'&&c.stats?`<div class="stats"><div><strong>${s.floor}/${s.target}</strong>${esc(t('progress'))}</div><div><strong>${s.errors}</strong>${esc(t('errors'))}</div><div><strong>${time(s.elapsed)}</strong>${esc(t('time'))}</div>${p.rules.bonus.enabled?`<div><strong>${Math.round(s.bonus*100)/100}</strong>${esc(p.rules.bonus.label||t('bonus'))}</div>`:''}</div>`:''}<button class="game-primary" data-action="${kind==='title'?'begin':'replay'}">${esc(kind==='title'?(c.button||t('start')):t('replay'))} <span>→</span></button></section></div>`;}
 function question(){const q=p.tasks[s.floor];if(!q)return '';let body='';if(['single','multiple'].includes(q.type)){body=`<div class="answers">${order.map(i=>`<label class="answer ${selected.includes(i)?'selected':''}"><input type="${q.type==='single'?'radio':'checkbox'}" name="answer" value="${i}" ${selected.includes(i)?'checked':''}><span>${esc(q.answers[i])}</span></label>`).join('')}</div>`;}else if(q.type==='text'){body=`<label class="text-answer">${esc(t('answer'))}<input id="typed-answer" autocomplete="off" ${q.numeric?'inputmode="decimal"':''}></label>`;}else if(q.type==='order'){body=`<div class="order-list">${order.map((i,n)=>`<div class="order-item" draggable="true" data-order="${n}"><span class="order-number">${n+1}</span><span>${esc(q.answers[i])}</span><button data-move="${n},-1" aria-label="${esc(t('up'))}: ${esc(q.answers[i])}" ${n===0?'disabled':''}>↑</button><button data-move="${n},1" aria-label="${esc(t('down'))}: ${esc(q.answers[i])}" ${n===order.length-1?'disabled':''}>↓</button></div>`).join('')}</div>`;}else body=`${q.oralMode==='teacher'?`<p class="teacher-note">${esc(t('teacher'))}</p>`:''}${sample?`<div class="sample">${esc(q.sample)}</div><div class="oral-buttons"><button class="game-primary" data-action="oral-yes">${esc(t('yes'))}</button><button class="game-secondary" data-action="oral-no">${esc(t('no'))}</button></div>`:`<button class="game-secondary" data-action="sample">${esc(t('sample'))}</button>`}`;
 return `<div class="task-overlay"><section class="task-card" role="dialog" aria-labelledby="question-heading"><small class="task-eyebrow">${esc(t('floor'))} ${s.floor+p.floors.start} <span>${s.floor+1} / ${s.target}</span></small><h2 id="question-heading">${esc(q.prompt)}</h2>${img(q.media,'task-media')}${body}<p class="feedback" role="status">${esc(feedback)}</p>${q.type!=='oral'?`<button class="game-primary" data-action="check">${esc(t('check'))} →</button>`:''}</section></div>`;
 }
 function render(){applyStyle();root.innerHTML=scene()+hud()+(editor?'':s.phase==='title'?screen('title'):['win','lose'].includes(s.phase)?screen(s.phase):s.phase==='task'?question():s.phase==='ready'?`<button class="game-primary start-task" data-action="ready">${esc(t('ready'))} →</button>`:'');}
 function focus(){root.querySelector('.task-card input,.task-card button,.screen-card button,.start-task,.floor-button.target')?.focus({preventScroll:true});}
 function task(){s.phase='task';s.taskElapsed=0;if(p.rules.timer.mode==='task')s.remaining=p.rules.timer.seconds;selected=[];sample=false;feedback='';const q=p.tasks[s.floor];order=q.answers.map((_,i)=>i);if(q.shuffle||q.type==='order'){for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}if(q.type==='order'&&order.every((v,i)=>v===i))order.reverse();}render();focus();}
 function answer(value){const q=p.tasks[s.floor],correct=checkAnswer(q,value);s=submit(p,s,value);sound(correct?'success':'error');feedback=correct?(q.onCorrect||p.rules.correct||t('correct')):(q.onWrong||p.rules.wrong||t('wrong'));render();focus();if(s.phase==='moving')defer(()=>{sound('arrival');task();},p.elevator.speed);}
 function click(e){const b=e.target.closest('button,[data-select]');if(!b)return;if(editor){if(b.closest('[data-select]')){root.querySelectorAll('.chosen').forEach(el=>el.classList.remove('chosen'));b.closest('[data-select]').classList.add('chosen');onSelect(b.closest('[data-select]').dataset.select);}return;}if(b.dataset.floor&&s.phase==='lobby'){s.target=Number(b.dataset.floor);s.phase='boarding';render();defer(()=>{s.phase='ready';render();focus();},p.elevator.doorSpeed*2+1);return;}if(b.dataset.move){const [n,delta]=b.dataset.move.split(',').map(Number);if(n+delta>=0&&n+delta<order.length){[order[n],order[n+delta]]=[order[n+delta],order[n]];render();root.querySelector(`[data-move="${n+delta},${delta}"]`)?.focus();}return;}const a=b.dataset.action;if(a==='begin'){s.phase='lobby';render();focus();}if(a==='replay'){clearTimeout(transition);s=initialGame(p);render();focus();}if(a==='ready')task();if(a==='sample'){sample=true;render();focus();}if(a==='oral-yes')answer(true);if(a==='oral-no')answer(false);if(a==='check'){const q=p.tasks[s.floor];if(['single','multiple'].includes(q.type)&&!selected.length)return;if(q.type==='text'&&!root.querySelector('#typed-answer').value.trim())return;answer(q.type==='order'?order:q.type==='text'?root.querySelector('#typed-answer').value:selected);}}
 root.addEventListener('click',click);const change=e=>{if(e.target.name==='answer'){const n=Number(e.target.value);if(p.tasks[s.floor].type==='single')selected=[n];else selected=e.target.checked?[...selected,n]:selected.filter(x=>x!==n);root.querySelectorAll('.answer').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked));}};root.addEventListener('change',change);
 const key=e=>{if(e.key==='Enter'&&e.target.id==='typed-answer'){e.preventDefault();root.querySelector('[data-action="check"]').click();}};root.addEventListener('keydown',key);
 let dragged=-1;const dragstart=e=>{dragged=Number(e.target.closest('[data-order]')?.dataset.order);e.dataTransfer?.setData('text/plain',String(dragged));},dragover=e=>{if(e.target.closest('[data-order]'))e.preventDefault();},drop=e=>{const target=e.target.closest('[data-order]');if(!target)return;e.preventDefault();const n=Number(target.dataset.order);if(Number.isInteger(dragged)&&dragged>=0&&dragged<order.length){const [v]=order.splice(dragged,1);order.splice(n,0,v);render();}dragged=-1;};root.addEventListener('dragstart',dragstart);root.addEventListener('dragover',dragover);root.addEventListener('drop',drop);
 const timer=setInterval(()=>{if(editor||disposed)return;const old=s.phase;s=tick(p,s);if(old!==s.phase){clearTimeout(transition);render();focus();}else{const el=root.querySelector('[data-time]');if(el){el.textContent=time(s.remaining);el.closest('.timer').classList.toggle('warning',s.remaining<=p.rules.timer.warning);}}},1000);render();
 return {update(next){p=next;if(editor){s=initialGame(p);render();}},setEditor(value){editor=value;clearTimeout(transition);s=initialGame(p);render();if(!editor)focus();},showTask(index=0){if(editor&&p.tasks[index]){s.floor=index;selected=[];order=p.tasks[index].answers.map((_,i)=>i);sample=false;feedback='';applyStyle();root.innerHTML=scene()+hud()+question();}},showScreen(kind){if(editor){applyStyle();root.innerHTML=scene()+hud()+screen(kind);}},destroy(){disposed=true;clearTimeout(transition);clearInterval(timer);audio?.close();root.removeEventListener('click',click);root.removeEventListener('change',change);root.removeEventListener('keydown',key);root.removeEventListener('dragstart',dragstart);root.removeEventListener('dragover',dragover);root.removeEventListener('drop',drop);},state:()=>structuredClone(s)};
}
