import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.BASE_URL||'http://127.0.0.1:8000';await mkdir('test-results',{recursive:true});
try{
 await page.goto(base);await page.waitForSelector('.floor-button');assert.equal(await page.locator('.floor-button').count(),5);console.log('PASS initial editor and five floors');
 for(const name of ['project','title','elevator','player','floors','tasks','style','rules','results','language','sound','export']){await page.locator(`[data-tab="${name}"]`).click();assert.ok(await page.locator('#settings h2').textContent());}console.log('PASS all 12 panels');
 await page.locator('[data-tab="project"]').click();await page.locator('[data-path="project.title"]').fill('Тестовый лифт');assert.equal(await page.locator('#project-heading').textContent(),'Тестовый лифт');await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('#project-heading').textContent(),'Моя игра');await page.locator('[data-action="redo"]').click();assert.equal(await page.locator('#project-heading').textContent(),'Тестовый лифт');console.log('PASS live updates, undo, redo');
 await page.locator('[data-tab="tasks"]').click();await page.locator('#new-task-type').selectOption('text');await page.locator('[data-action="add-task"]').click();assert.equal(await page.locator('.floor-button').count(),6);await page.locator('[data-action="duplicate-task"]').click();assert.equal(await page.locator('.floor-button').count(),7);await page.locator('[data-action="delete-task"]').click();await page.locator('#confirm').click();assert.equal(await page.locator('.floor-button').count(),6);await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('.floor-button').count(),7);await page.locator('[data-action="undo"]').click();await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('.floor-button').count(),5);console.log('PASS add, duplicate, delete and floor sync');
 await page.locator('[data-action="test"]').click();await page.locator('[data-action="begin"]').click();await page.locator('[data-lift="skyline"]').click();await page.locator('[data-floor="5"]').click();await page.locator('[data-action="ready"]').click();await page.locator('.answer input[value="0"]').check();await page.locator('[data-action="check"]').click();assert.equal(await page.locator('.hud-pill b').first().textContent(),'2');assert.match(await page.locator('.lift-sign').textContent(),/00/);await page.locator('.answer input[value="1"]').check();await page.locator('[data-action="check"]').click();await page.waitForFunction(()=>document.querySelector('#question-heading')?.textContent.includes('чётные'));await page.locator('.answer input[value="0"]').check();await page.locator('.answer input[value="2"]').check();await page.locator('[data-action="check"]').click();await page.waitForSelector('.order-list');
 for(let wanted=0;wanted<4;wanted++){let texts=await page.locator('.order-item>span:nth-child(2)').allTextContents();let pos=texts.indexOf(['3','7','12','20'][wanted]);while(pos>wanted){await page.locator(`[data-move="${pos},-1"]`).click();pos--;}}
 await page.locator('[data-action="check"]').click();await page.waitForSelector('#typed-answer');await page.locator('#typed-answer').fill('земля');await page.locator('#typed-answer').press('Enter');await page.waitForSelector('[data-action="sample"]');await page.locator('[data-action="sample"]').click();await page.locator('[data-action="oral-yes"]').click();assert.equal(await page.locator('.screen-card h1').textContent(),'Ты на высоте!');console.log('PASS full five-task game, retry and victory');
 await page.locator('[data-action="replay"]').click();await page.locator('[data-action="begin"]').click();await page.locator('[data-lift="skyline"]').click();await page.locator('[data-floor="5"]').click();await page.locator('[data-action="ready"]').click();for(let i=0;i<3;i++){await page.locator('.answer input[value="0"]').check();await page.locator('[data-action="check"]').click();}assert.equal(await page.locator('.screen-card h1').textContent(),'Попробуем ещё раз?');console.log('PASS defeat at zero lives');
 await page.locator('[data-action="edit"]').click();await page.locator('[data-tab="language"]').click();await page.locator('[data-path="project.locale"]').selectOption('ar');assert.equal(await page.locator('#game').getAttribute('dir'),'rtl');await page.locator('[data-path="project.locale"]').selectOption('en');await page.locator('[data-action="test"]').click();assert.match(await page.locator('[data-action="begin"]').textContent(),/Begin/);await page.locator('[data-action="edit"]').click();await page.locator('[data-path="project.locale"]').selectOption('ru');console.log('PASS localization and RTL');
 const media=await page.evaluate(async()=>{const {optimize}=await import('/src/media/media.js'),{defaults}=await import('/src/game/model.js');const p=defaults(),c=document.createElement('canvas');c.width=3200;c.height=2400;c.getContext('2d').fillRect(0,0,3200,2400);const file=new File([await new Promise(r=>c.toBlob(r,'image/png'))],'large.png',{type:'image/png'}),a=await optimize(file,'background',p),im=await createImageBitmap(await (await fetch(a.data)).blob());const bytes=Uint8Array.from(atob('R0lGODlhAQABAIAAAAAAAP///yH5BAAKAAAALAAAAAABAAEAAAICRAEAOw=='),c=>c.charCodeAt(0)),frame=bytes.slice(19,-1),frame2=frame.slice();frame2[20]=76;const gif=new File([bytes.slice(0,19),frame,frame2,new Uint8Array([59])],'animated.gif',{type:'image/gif'}),g=await optimize(gif,'character',p);const decoder=new ImageDecoder({data:await(await fetch(g.data)).arrayBuffer(),type:'image/gif'});await decoder.tracks.ready;const frames=decoder.tracks.selectedTrack.frameCount;decoder.close();const {draft,projectBlob,readProject}=await import('/src/storage/storage.js');p.assets=[a,g];p.player.media=g.id;p.theme.backgroundImage=a.id;await draft('put',p);const saved=await draft('get'),roundtrip=await readProject(projectBlob(saved));return {frames,width:im.width,height:im.height,type:a.type,gif:g.type,roundtrip:roundtrip.assets[1].data===g.data,warning:g.warning};});assert.ok(media.width<=1920&&media.height<=1080);assert.equal(media.type,'image/webp');assert.equal(media.gif,'image/gif');assert.equal(media.frames,2);assert.equal(media.roundtrip,true);console.log('PASS image worker resize and GIF optimizer',media.warning||'');
 const exports=await page.evaluate(async()=>{const {gameHTML}=await import('/src/export/export.js'),{defaults}=await import('/src/game/model.js'),p=defaults();p.project.title='Safe </script><script>window.hacked=1</script>';const locales={ru:await(await fetch('/src/locales/ru.json')).json()};return {normal:await gameHTML(p,locales),light:await gameHTML(p,locales,true)};});assert.ok(Buffer.byteLength(exports.light)<=Buffer.byteLength(exports.normal));assert.ok(!exports.normal.includes('Все права защищены'));await writeFile('test-results/game.html',exports.normal);await writeFile('test-results/light-game.html',exports.light);
 const exported=await context.newPage();const requests=[];exported.on('pageerror',e=>errors.push(e.message));exported.on('request',r=>{if(!r.url().startsWith('file:')&&!r.url().startsWith('data:'))requests.push(r.url());});await context.setOffline(true);await exported.goto('file://'+process.cwd()+'/test-results/game.html');await exported.locator('[data-action="begin"]').click();await exported.locator('[data-lift="skyline"]').click();await exported.locator('[data-floor="5"]').click();await exported.locator('[data-action="ready"]').click();await exported.locator('.answer input[value="1"]').check();await exported.locator('[data-action="check"]').click();await exported.waitForFunction(()=>document.querySelector('#question-heading')?.textContent.includes('чётные'));assert.equal(await exported.evaluate(()=>window.hacked),undefined);assert.equal(requests.length,0);await exported.goto('file://'+process.cwd()+'/test-results/light-game.html');await exported.waitForSelector('[data-action="begin"]');await context.setOffline(false);await exported.close();console.log('PASS both standalone exports offline, no network requests, script injection escaped');
 await page.locator('[data-tab="project"]').click();await page.locator('[data-path="project.title"]').fill('Проверка восстановления');await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Черновик сохранён'));await page.reload();await page.locator('#restore').click();assert.equal(await page.locator('#project-heading').textContent(),'Проверка восстановления');console.log('PASS IndexedDB restore');
 await page.screenshot({path:'test-results/editor-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/editor-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-action="test"]').click();await page.locator('[data-action="begin"]').click();await page.locator('[data-lift="skyline"]').click();await page.locator('[data-floor="5"]').click();await page.locator('[data-action="ready"]').click();await page.locator('#game').screenshot({path:'test-results/game-mobile.png'});console.log('PASS mobile layout');assert.deepEqual(errors,[]);console.log('PASS no JavaScript errors');
}finally{await browser.close();}
