import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,checkAnswer,initialGame,submit,tick,validate,newTask} from '../src/game/model.js';
import {migrate} from '../src/storage/schema.js';
import {projectBlob,readProject} from '../src/storage/storage.js';
import {embedCode} from '../src/export/export.js';
test('all five answer types; exact sets, normalized alternatives, numeric tolerance',()=>{const p=defaults();assert.equal(checkAnswer(p.tasks[0],[1]),true);assert.equal(checkAnswer(p.tasks[0],[0]),false);assert.equal(checkAnswer(p.tasks[1],[2,0]),true);assert.equal(checkAnswer(p.tasks[1],[0]),false);assert.equal(checkAnswer(p.tasks[2],[0,1,2,3]),true);assert.equal(checkAnswer(p.tasks[2],[0,2,1,3]),false);assert.equal(checkAnswer(p.tasks[3],' З Е М Л Я '),true);assert.equal(checkAnswer(newTask('oral'),true),true);const n={...newTask('text'),numeric:true,tolerance:.1,accepted:['3.14']};assert.equal(checkAnswer(n,'3,2'),true);assert.equal(checkAnswer(n,''),false);assert.equal(checkAnswer(n,'x'),false);});
test('wrong answer consumes one life and advances without repeating the task',()=>{const p=defaults();let s={...initialGame(p),phase:'task'};s=submit(p,s,[0]);assert.equal(s.lives,2);assert.equal(s.floor,1);assert.equal(s.phase,'moving');assert.equal(s.bonus,0);s.phase='task';s=submit(p,s,[0,2]);assert.equal(s.floor,2);assert.equal(s.lives,2);});
test('last life allows victory; zero lives stops play',()=>{const p=defaults();let s={...initialGame(p),phase:'task',lives:1,target:1};assert.equal(submit(p,s,[1]).arrival,'win');s=submit(p,s,[0]);assert.equal(s.phase,'lose');assert.equal(submit(p,s,[1]).floor,0);});
test('free goal and automatic top goal',()=>{const p=defaults();assert.equal(initialGame(p).target,4);p.floors.target=2;assert.equal(initialGame(p).target,2);});
test('mandatory/informational timers and off timer',()=>{const p=defaults();let s={...initialGame(p),phase:'task',remaining:1};assert.equal(tick(p,s).remaining,1);p.rules.timer.mode='game';assert.equal(tick(p,s).phase,'lose');p.rules.timer.mandatory=false;assert.equal(tick(p,s).phase,'task');p.rules.timer.mode='task';assert.equal(tick(p,{...s,phase:'moving'}).remaining,1);});
test('bonus off, no partial-credit farming, bonuses do not change goal',()=>{const p=defaults();p.rules.bonus.enabled=false;assert.equal(submit(p,{...initialGame(p),phase:'task'},[1]).bonus,0);p.rules.bonus.enabled=true;p.tasks[1].partial=true;let s={...initialGame(p),phase:'task',floor:1,lives:10};s=submit(p,s,[0]);const bonus=s.bonus;s.phase='task';s.floor=1;s=submit(p,s,[0]);assert.equal(s.bonus,bonus);assert.equal(s.floor,2);assert.equal(s.bonus,0);});
test('export validation rejects empty project and missing correct answer',()=>{const p=defaults();assert.equal(validate(p).length,0);p.tasks[0].correct=[];assert.ok(validate(p).length);p.tasks=[];assert.ok(validate(p).length);});
test('zip round trip includes assets and all settings',async()=>{const p=defaults();p.assets=[{id:'hero',name:'test.gif',type:'image/gif',original:6,size:6,data:'data:image/gif;base64,R0lGODlh'}];p.player.media='hero';const result=await readProject(projectBlob(p));assert.equal(result.player.media,'hero');assert.equal(result.assets[0].data,p.assets[0].data);assert.equal(result.tasks[3].sample,p.tasks[3].sample);assert.deepEqual(result.rules,p.rules);});
test('invalid archives and unsupported schemas cannot overwrite project',async()=>{await assert.rejects(()=>readProject(new Blob(['bad'])));assert.throws(()=>migrate({...defaults(),version:999}));const p=defaults();p.theme.accent='red; background:url(https://evil)';assert.throws(()=>migrate(p));assert.throws(()=>migrate(JSON.parse('{"version":1,"__proto__":{"x":1}}')));});
test('embed requires HTTPS, escapes title and URL',()=>{assert.throws(()=>embedCode('javascript:alert(1)','a'));assert.throws(()=>embedCode('http://site.com','a'));const s=embedCode('https://example.com/game.html?a=1&b=2','<game>');assert.ok(s.includes('aspect-ratio:16/9'));assert.ok(s.includes('&lt;game&gt;'));assert.ok(s.includes('&amp;b=2'));});

test('wrong final answer still reaches the goal if a life remains; last life ends in defeat',()=>{const p=defaults();const s={...initialGame(p),phase:'task',target:1,lives:2};const next=submit(p,s,[0]);assert.equal(next.floor,1);assert.equal(next.lives,1);assert.equal(next.arrival,'win');assert.equal(next.phase,'moving');assert.equal(submit(p,{...s,lives:1},[0]).phase,'lose');});
test('old projects gain layers and frame and cannot enable student lift choice',()=>{const p=defaults();delete p.layers;delete p.sceneFrame;p.elevator.studentChoice=true;const restored=migrate(p);assert.equal(restored.elevator.studentChoice,false);assert.deepEqual(restored.layers,defaults().layers);assert.deepEqual(restored.sceneFrame,defaults().sceneFrame);restored.sceneFrame.width=6;restored.sceneFrame.style='dashed';assert.deepEqual(migrate(restored).sceneFrame,restored.sceneFrame);restored.sceneFrame.glow=-1;assert.throws(()=>migrate(restored));});
test('all cheat-sheet LaTeX constructions render without errors',()=>{
 const examples=[String.raw`\frac{x+1}{y-2}`,String.raw`x^{10}+a_{n+1}`,String.raw`\sqrt[n]{a}`,String.raw`\left(\frac{a}{b}\right)`,String.raw`\left[x+1\right]`,String.raw`\left|x\right|`,String.raw`\times\cdot\div\pm\neq\leq\geq\infty\pi\approx`,String.raw`\sum_{i=1}^{n}i`,String.raw`\lim_{x\to0}f(x)`,String.raw`25\%`,String.raw`\angle ABC+90^\circ+\triangle ABC`,String.raw`a\parallel b\perp c`,String.raw`\overline{AB}`,String.raw`S=24\text{ см}^2`,String.raw`v=60\text{ км/ч}`,String.raw`\frac{-b\pm\sqrt{b^2-4ac}}{2a}`,String.raw`\begin{cases}x+y=5\\x-y=1\end{cases}`];
 for(const formula of examples)assert.match(globalThis.katex.renderToString(formula,{output:'mathml',trust:false,strict:'ignore'}),/<math/);
});
test('custom styling and goal survive project archive, legacy reflection is removed',async()=>{
 const p=defaults();p.buttons.enter.background='#123456';p.buttons.check.glow=24;p.displayStyle.digits='segments';p.theme.font='Courier New';p.floors.goalText='Этаж {floor}!';
 const r=await readProject(projectBlob(p));assert.deepEqual(r.buttons,p.buttons);assert.deepEqual(r.displayStyle,p.displayStyle);assert.equal(r.theme.font,p.theme.font);assert.equal(r.floors.goalText,p.floors.goalText);
 p.tasks.push({...newTask('oral'),prompt:'Что нового ты узнал сегодня?',sample:'Расскажи о том, что получилось, и о том, что хотелось бы повторить.'});p.floors.target=5;assert.equal(migrate(p).tasks.length,4);assert.equal(migrate(p).floors.target,4);
 p.tasks.at(-1).prompt='Расскажи решение задачи';assert.equal(migrate(p).tasks.length,5);
 p.buttons.check.glow=-1;assert.throws(()=>migrate(p));
});
test('button effects, sizes, question/answer styles and entry placement survive saving',async()=>{const p=defaults();p.buttons.enter.effect='wobble';p.buttons.enter.scale=1.6;p.layout.enter={x:33,y:80,scale:1.2};p.theme.fontSize=44;p.theme.answerFontSize=30;p.theme.answerColor='#123456';const r=await readProject(projectBlob(p));assert.deepEqual(r.buttons,p.buttons);assert.deepEqual(r.layout.enter,p.layout.enter);assert.equal(r.theme.fontSize,44);assert.equal(r.theme.answerFontSize,30);assert.equal(r.theme.answerColor,'#123456');p.buttons.enter.effect='invalid';assert.throws(()=>migrate(p));});
