import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.BASE_URL||'http://127.0.0.1:8000';await mkdir('test-results',{recursive:true});
try{
 await page.addInitScript(()=>{window.__audioCalls={oscillator:0,buffer:0};const proto=(window.AudioContext||window.webkitAudioContext).prototype;for(const[key,name]of [['createOscillator','oscillator'],['createBufferSource','buffer']]){const original=proto[key];proto[key]=function(...args){window.__audioCalls[name]++;return original.apply(this,args);};}});
 await page.goto(base);await page.waitForSelector('.floor-button');
 assert.equal(await page.locator('.plant,.architecture,.scene-heading,.floor-lines').count(),0);
 const centered=await page.evaluate(()=>{const a=document.querySelector('#game').getBoundingClientRect(),b=document.querySelector('.start-task').getBoundingClientRect();return [Math.abs((b.x+b.width/2)-(a.x+a.width/2)),Math.abs((b.y+b.height/2)-(a.y+a.height/2))];});assert.ok(centered.every(n=>n<2));
 const fit=await page.evaluate(()=>{const a=document.querySelector('#game').getBoundingClientRect(),b=document.querySelector('.lift').getBoundingClientRect();return {width:b.width/a.width,height:b.height/a.height,left:b.left>=a.left-1,right:b.right<=a.right+1};});assert.ok(fit.width>.98&&fit.height>.98&&fit.left&&fit.right);console.log('PASS full slide, centered Start and removed decorations');
 await page.locator('[data-tab="elevator"]').click();assert.equal(await page.locator('[data-design]').count(),3);await page.locator('[data-design="aurora"]').click();assert.match(await page.locator('#game').getAttribute('class'),/design-aurora/);await page.locator('[data-path="theme.background"]').fill('#dae9e2');assert.equal(await page.locator('.scene').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(218, 233, 226)');console.log('PASS lift asset picker and plain configurable background');
 const hero=page.locator('.hero');const old=await hero.boundingBox();await page.mouse.move(old.x+old.width/2,old.y+old.height/2);await page.mouse.down();await page.mouse.move(old.x+old.width/2+65,old.y+old.height/2-35,{steps:8});await page.mouse.up();assert.equal(await page.locator('.hero.chosen').count(),1);const changed=await hero.boundingBox();assert.ok(changed.x>old.x+40);assert.equal(await hero.evaluate(el=>getComputedStyle(el).outlineStyle),'dashed');await page.locator('[data-action="undo"]').click();const undone=await hero.boundingBox();assert.ok(Math.abs(undone.x-old.x)<2);await hero.focus();await page.keyboard.press('ArrowRight');const nudged=await hero.boundingBox();assert.ok(nudged.x>old.x+4);console.log('PASS dashed selection, pointer drag, undo and keyboard movement');
 await page.locator('[data-tab="sound"]').click();assert.equal(await page.locator('[data-sound]').count(),5);for(const kind of ['door','travel','arrival','success','error'])await page.locator(`[data-sound="${kind}"]`).click();const sounds=await page.evaluate(()=>window.__audioCalls);assert.ok(sounds.oscillator>=9&&sounds.buffer>=1);console.log('PASS each sound preview generates audio sources');
 await page.locator('[data-action="test"]').click();await page.locator('[data-action="begin"]').click();assert.equal(await page.locator('[data-lift]').count(),1);await page.locator('#game').screenshot({path:'test-results/lift-choice.png'});await page.locator('[data-lift="aurora"]').click();await page.waitForFunction(()=>document.querySelector('#game').dataset.boardStep==='walking');const startX=await page.locator('.entry-hero').evaluate(el=>el.getBoundingClientRect().height);await page.waitForTimeout(750);const midX=await page.locator('.entry-hero').evaluate(el=>el.getBoundingClientRect().height);assert.ok(midX<startX-5);await page.locator('#game').screenshot({path:'test-results/lift-boarding.png'});await page.waitForSelector('#game.choose');assert.equal(await page.locator('.floor-button:enabled').count(),4);await page.locator('[data-floor="2"]').click();assert.match(await page.locator('.goal-badge').textContent(),/Этаж 2/);assert.match(await page.locator('#game').getAttribute('class'),/design-aurora/);await page.locator('#game').screenshot({path:'test-results/lift-cabin.png'});console.log('PASS visible entry animation, interior floor selection, goal and editor-only lift choice');
 await page.locator('[data-action="go-back"]').click();assert.equal(await page.locator('[data-lift]').count(),1);await page.locator('[data-lift="aurora"]').click();await page.waitForSelector('#game.choose');await page.locator('[data-floor="2"]').click();await page.locator('[data-action="ready"]').click();await page.locator('.answer input[value="1"]').check();await page.locator('[data-action="check"]').click();await page.waitForFunction(()=>document.querySelector('#question-heading')?.textContent.includes('чётные'));await page.locator('.answer input[value="1"]').check();await page.locator('[data-action="check"]').click();assert.equal(await page.locator('.display-arrow').textContent(),'↑');assert.match(await page.locator('#question-heading').textContent(),/чётные/);assert.equal(await page.locator('.display-number').textContent(),'01');assert.equal(await page.locator('.hud-pill b').first().textContent(),'2');console.log('PASS return arrow and life loss without changing floor');
 await page.locator('[data-action="edit"]').click();await page.locator('[data-action="light"]').first().click();await page.waitForFunction(()=>document.querySelector('#embed-status')?.textContent.includes('Код готов'));const light=await page.locator('#embed-output').inputValue();assert.ok(light.includes('<iframe'));assert.ok(/\/players\/v-[a-f0-9]+\/play.html#project=/.test(light));assert.match(await page.locator('#embed-size').textContent(),/Экономия:/);await page.locator('#copy-embed').click();assert.equal(await page.locator('#embed-output').inputValue(),light);await page.locator('#dialog [data-action="close"]').click();await page.locator('.top-actions [data-action="embed"]').click();await page.waitForFunction(()=>document.querySelector('#embed-status')?.textContent.includes('Код готов'));const normal=await page.locator('#embed-output').inputValue();assert.ok(light.length<normal.length);console.log('PASS ready Genially code, compression savings and clipboard fallback');
 const src=light.match(/src="([^"]+)"/)[1].replaceAll('&amp;','&');const shared=await context.newPage();shared.on('pageerror',e=>errors.push(e.message));await shared.goto(base+new URL(src).pathname.replace(/^\/lift/,'')+new URL(src).hash);await shared.locator('[data-action="begin"]').click();await shared.locator('[data-lift="aurora"]').click();await shared.waitForSelector('#game.choose');await shared.locator('[data-floor="1"]').click();await shared.locator('[data-action="ready"]').click();await shared.locator('.answer input[value="1"]').check();await shared.locator('[data-action="check"]').click();await shared.waitForSelector('#game.win');console.log('PASS actual embedded player restores and plays exact project');
 await shared.setViewportSize({width:640,height:360});assert.ok(await shared.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));await shared.screenshot({path:'test-results/embedded-game.png'});await shared.close();await page.locator('#dialog [data-action="close"]').click();await page.screenshot({path:'test-results/revised-editor.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS no uncaught browser errors');
}finally{await browser.close();}
