import {initialGame,submit,tick,checkAnswer} from './model.js';
import {LIFT_DESIGNS} from './lifts.js';
import {createAudio} from './audio.js';
import {renderMath} from './math.js';
export function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function createGame(root,project,dictionaries,{editor=false,onSelect=()=>{},onMove=()=>{}}={}){
 let p=project,s=initialGame(p),selected=[],order=[],sample=false,feedback='',disposed=false,view='cabin',selection='',previewScreen='',transition=0;
 const audio=createAudio(()=>p.elevator),esc=escapeHTML,t=k=>dictionaries[p.project.locale]?.[k]||dictionaries[p.project.fallback]?.[k]||dictionaries.ru?.[k]||k;
 const asset=id=>p.assets.find(a=>a.id===id)?.data||'';
 const img=(id,cls='')=>asset(id)?`<img class="${cls}" src="${asset(id)}" alt="">`:'';
 const time=n=>Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toString().padStart(2,'0');
 const motion=()=>p.elevator.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
 function defer(fn,seconds){clearTimeout(transition);transition=setTimeout(()=>{if(!disposed)fn();},motion()?seconds*1000:25);}
 function sound(kind){void audio.play(kind);}
 const names={elevator:'Лифт',player:'Персонаж',floors:'Пульт этажей',start:'Кнопка «Старт»',goal:'Цель',display:'Табло',hud:'Индикаторы'};
 function place(key,extra=''){const pos=p.layout[key];return `data-select="${key}" data-name="${names[key]}" ${editor?`tabindex="0" aria-label="${names[key]}: перетащите или используйте стрелки"`:''} style="--x:${pos.x}%;--y:${pos.y}%;--object-scale:${pos.scale};z-index:${p.layers?.[key]||1};${extra}"`;}
 function applyStyle(){
  const design=LIFT_DESIGNS[editor?p.elevator.design:s.design]||LIFT_DESIGNS.skyline;
  const same=editor||s.design===p.elevator.design;
  const vars={'accent':same?p.theme.accent:design.accent,'bg':p.theme.background,'ink':p.theme.text,'panel':p.theme.panel,'door':same?p.theme.door:design.door,'frame':same?p.theme.frame:design.frame,'wall':design.wall,'radius':p.theme.radius+'px','font':p.theme.font,'task-size':p.theme.fontSize+'px','border':p.theme.border,'shadow':p.theme.shadow+'px','opacity':p.theme.opacity/100,'task-width':p.theme.taskWidth+'%','pad':p.theme.padding+'px','button-radius':p.theme.buttonRadius+'px','button-color':p.theme.buttonColor,'button-text':p.theme.buttonText,'line-height':p.theme.lineHeight,'align':p.theme.align,'weight':p.theme.bold?'700':'400','hero-scale':p.player.scale,'hero-flip':p.player.flip?-1:1,'door-speed':p.elevator.doorSpeed+'s','travel-speed':p.elevator.speed+'s','cols':p.floors.columns,'floor-size':p.floors.size+'px','floor-radius':p.floors.round?'50%':'10px'};
  for(const[k,v]of Object.entries(vars))root.style.setProperty('--'+k,v);
  for(const [key,b] of Object.entries(p.buttons||{}))for(const [name,value] of Object.entries(b))root.style.setProperty('--'+key+'-'+name,name==='glow'?value+'px':value);
  for(const [key,value] of Object.entries(p.displayStyle||{}))root.style.setProperty('--display-'+key,key==='glow'?value+'px':value);
  root.dataset.digits=p.displayStyle?.digits||'classic';
  const f=p.sceneFrame;if(f){root.style.borderRadius=f.radius+'px';root.style.setProperty('--scene-line',`${f.width}px ${f.style} ${f.color}`);root.style.setProperty('--scene-glow',`inset 0 0 ${f.glow}px ${f.glowColor}`);}
  root.dir=p.project.locale==='ar'?'rtl':'ltr';root.className=`game ${motion()?'':'still'} ${editor?'editing':''} ${s.phase} design-${editor?p.elevator.design:s.design} view-${editor?view:['title','lobby','boarding'].includes(s.phase)?'lobby':'cabin'}`;
 }
 const robot=`<div class="robot"><div class="antenna"></div><div class="robot-head"><div class="robot-face"><i></i><i></i><b></b></div></div><div class="robot-body"><span>✦</span></div><div class="robot-arm left"></div><div class="robot-arm right"></div><div class="robot-foot left"></div><div class="robot-foot right"></div></div>`;
 const hero=()=>asset(p.player.media)?img(p.player.media):robot;
 function shell(cabin){return `<div class="scene-object lift ${cabin?'cabin-shell':'exterior-shell'}" ${place('elevator')}><div class="lift-edge"></div><div class="portal-interior"><div class="ceiling-light"></div></div>${s.phase==='boarding'&&!editor?`<div class="entry-hero" style="--entry-x:${50+(p.layout.player.x-p.layout.elevator.x)/p.layout.elevator.scale}%;--entry-y:${50+(p.layout.player.y-p.layout.elevator.y)/p.layout.elevator.scale}%;--entry-scale:${p.player.scale*p.layout.player.scale/p.layout.elevator.scale}">${hero()}</div>`:''}<div class="portal"><div class="lift-door door-left"><span></span></div><div class="lift-door door-right"><span></span></div></div><div class="threshold"></div>${cabin?'<div class="cabin-floor"></div><div class="cabin-handrail"></div>':''}</div>`;}
 function displayNumber(){const value=String(s.floor+p.floors.start-1).padStart(2,'0');if(p.displayStyle?.digits!=='segments')return esc(value);const codes=['abcdef','bc','abdeg','abcdg','bcfg','acdfg','acdefg','abc','abcdefg','abcdfg'],segments={a:[4,1,16,3],b:[20,4,3,17],c:[20,24,3,17],d:[4,41,16,3],e:[1,24,3,17],f:[1,4,3,17],g:[4,21,16,3]};return `<span class="segment-digits" role="img" aria-label="${value}">${[...value].map(n=>`<svg viewBox="0 0 24 45" aria-hidden="true">${Object.entries(segments).map(([key,box])=>`<rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}" rx="1" opacity="${(codes[Number(n)]||'g').includes(key)?1:.12}"/>`).join('')}</svg>`).join('')}</span>`;}
 function goalText(goal){const label=editor||s.targetSelected?String(goal+p.floors.start-1):t('choose');return p.floors.goalText?esc(p.floors.goalText.replaceAll('{floor}',label)):`${esc(t('goal'))}: ${esc(t('floor'))} ${esc(label)}`;}
 function scene(){
  const cabin=editor?view==='cabin':!['title','lobby','boarding'].includes(s.phase);
  const pick=false;
  const goal=editor?(p.floors.target||p.tasks.length):s.target;
  const canChoose=s.phase==='choose'||s.phase==='ready';
  return `<div class="scene">${asset(p.theme.backgroundImage)?`<img class="scene-bg" src="${asset(p.theme.backgroundImage)}" style="object-fit:${p.theme.fit==='contain'?'contain':'cover'};opacity:${p.theme.imageOpacity/100}" alt="">`:''}${shell(cabin)}${!pick?`<div class="scene-object lift-sign" ${place('display')}><button data-action="go-back" aria-label="${esc(t('back'))}" ${!editor&&!canChoose?'disabled':''}>↶</button><span class="display-number">${displayNumber()}</span><span class="display-arrow ${s.direction==='down'?'down':''}" aria-label="${esc(t(s.direction==='down'?'down':'up'))}">${s.direction==='down'?'↓':'↑'}</span></div>`:''}${cabin||editor?`<div class="scene-object goal-badge" ${place('goal')}><span data-math>${goalText(goal)}</span></div><div class="scene-object floor-console" ${place('floors')}><div class="console-label">${esc(t('choose'))}</div><div class="floor-grid">${p.tasks.map((_,i)=>`<button data-floor="${i+1}" class="floor-button ${i<s.floor?'passed':''} ${(editor||s.targetSelected)&&i+1===goal?'target':''}" ${!editor&&(!canChoose||(p.floors.mode==='fixed'&&i+1!==s.target))?'disabled':''} aria-label="${esc(t('floor'))} ${i+p.floors.start}">${i+p.floors.start}</button>`).join('')}</div><small>${esc(t('progress'))} <b>${s.floor} / ${s.target}</b></small></div>`:''}${!pick&&s.phase!=='boarding'?`<div class="scene-object hero ${p.player.idle?'idle':''}" ${place('player')}><div class="hero-content">${hero()}</div></div>`:''}${(cabin&&(editor||canChoose))?`<div class="scene-object start-control" ${place('start')}><button class="game-primary start-task" data-action="ready" ${!editor&&!s.targetSelected?'disabled':''}>${esc(t('ready'))} <span>↑</span></button></div>`:''}${((editor&&view==='lobby')||(!editor&&s.phase==='lobby'))?`<button class="game-primary enter-control" data-lift="${esc(p.elevator.design)}">${esc(t('enterLift'))} →</button>`:''}<div class="scene-caption" role="status">${esc(s.phase==='boarding'?t('enter'):['moving','descending'].includes(s.phase)?feedback:'')}</div></div>`;
 }
 function hud(){return `<div class="scene-object game-hud" ${place('hud')}><span class="hud-pill">${p.rules.lifeMedia?img(p.rules.lifeMedia,'life-icon'):esc(p.rules.lifeIcon)} <b>${editor?p.rules.lives:s.lives}</b><small>${esc(t('lives'))}</small></span>${p.rules.timer.mode!=='off'?`<span class="hud-pill timer ${s.remaining<=p.rules.timer.warning?'warning':''}">◷ <b data-time>${time(editor?p.rules.timer.seconds:s.remaining)}</b><small>${esc(t('time'))}</small></span>`:''}${p.rules.bonus.enabled?`<span class="hud-pill bonus">✦ <b>${Math.round(s.bonus*100)/100}</b><small>${esc(p.rules.bonus.label||t('bonus'))}</small></span>`:''}</div>`;}
 function screen(kind){const c=p.screens[kind];return `<div class="screen-overlay" style="background:${c.background}f2"><section class="screen-card ${c.glow?'glow':''}" style="${kind==='title'?`color:${c.color};--screen-title:${c.size}px`:''}" role="dialog" aria-label="${esc(c.title)}">${img(c.media,'screen-media')}<div class="screen-emblem">${kind==='title'?'↑':kind==='win'?'✦':'↻'}</div><h1 data-math>${esc(c.title)}</h1><p data-math>${esc(c.description)}</p>${kind!=='title'&&c.stats?`<div class="stats"><div><strong>${s.floor}/${s.target}</strong>${esc(t('progress'))}</div><div><strong>${s.errors}</strong>${esc(t('errors'))}</div><div><strong>${time(s.elapsed)}</strong>${esc(t('time'))}</div>${p.rules.bonus.enabled?`<div><strong>${Math.round(s.bonus*100)/100}</strong>${esc(p.rules.bonus.label||t('bonus'))}</div>`:''}</div>`:''}<button class="game-primary" data-action="${kind==='title'?'begin':'replay'}">${esc(kind==='title'?(c.button||t('start')):t('replay'))} →</button></section></div>`;}
 function question(){const q=p.tasks[s.floor];if(!q)return '';let body='';if(['single','multiple'].includes(q.type)){body=`<div class="answers">${order.map(i=>`<label class="answer ${selected.includes(i)?'selected':''}"><input type="${q.type==='single'?'radio':'checkbox'}" name="answer" value="${i}" ${selected.includes(i)?'checked':''}><span data-math>${esc(q.answers[i])}</span></label>`).join('')}</div>`;}else if(q.type==='text'){body=`<label class="text-answer">${esc(t('answer'))}<input id="typed-answer" autocomplete="off" ${q.numeric?'inputmode="decimal"':''}></label>`;}else if(q.type==='order'){body=`<div class="order-list">${order.map((i,n)=>`<div class="order-item" draggable="true" data-order="${n}"><span class="order-number">${n+1}</span><span data-math>${esc(q.answers[i])}</span><button data-move="${n},-1" aria-label="${esc(t('up'))}: ${esc(q.answers[i])}" ${n===0?'disabled':''}>↑</button><button data-move="${n},1" aria-label="${esc(t('down'))}: ${esc(q.answers[i])}" ${n===order.length-1?'disabled':''}>↓</button></div>`).join('')}</div>`;}else body=`${q.oralMode==='teacher'?`<p class="teacher-note">${esc(t('teacher'))}</p>`:''}${sample?`<div class="sample" data-math>${esc(q.sample)}</div><div class="oral-buttons"><button class="game-primary" data-action="oral-yes">${esc(t('yes'))}</button><button class="game-secondary" data-action="oral-no">${esc(t('no'))}</button></div>`:`<button class="game-secondary" data-action="sample">${esc(t('sample'))}</button>`}`;
 return `<div class="task-overlay"><section class="task-card" role="dialog" aria-labelledby="question-heading"><small class="task-eyebrow">${esc(t('floor'))} ${s.floor+p.floors.start} <span>${s.floor+1} / ${s.target}</span></small><h2 id="question-heading" data-math>${esc(q.prompt)}</h2>${img(q.media,'task-media')}${body}<p class="feedback" role="status" data-math>${esc(feedback)}</p>${q.type!=='oral'?`<button class="game-primary" data-action="check">${esc(t('check'))} →</button>`:''}</section></div>`;
 }
 function render(){applyStyle();root.innerHTML=scene()+hud()+(editor?(previewScreen==='task'?question():previewScreen?screen(previewScreen):''):s.phase==='title'?screen('title'):['win','lose'].includes(s.phase)?screen(s.phase):s.phase==='task'?question():'');renderMath(root);if(editor&&selection)root.querySelector(`[data-select="${selection}"]`)?.classList.add('chosen');}
 function focus(){root.querySelector('.task-card input,.task-card button,.screen-card button,.lift-choice,.floor-button.target,.floor-button,.start-task')?.focus({preventScroll:true});}
 function task(keepFeedback=false){s.phase='task';s.taskElapsed=0;s.taskErrors=s.errorsByFloor?.[s.floor]||0;if(p.rules.timer.mode==='task')s.remaining=p.rules.timer.seconds;selected=[];sample=false;if(!keepFeedback)feedback='';const q=p.tasks[s.floor];order=q.answers.map((_,i)=>i);if(q.shuffle||q.type==='order'){for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}if(q.type==='order'&&order.every((v,i)=>v===i))order.reverse();}render();focus();}
 function board(design){s.design=p.elevator.design;s.phase='boarding';render();sound('door');root.dataset.boardStep='opening';defer(()=>{root.dataset.boardStep='approaching';defer(()=>{root.dataset.boardStep='walking';defer(()=>{root.dataset.boardStep='closing';sound('door');defer(()=>{delete root.dataset.boardStep;s.phase='choose';s.targetSelected=p.floors.mode==='fixed';render();focus();sound('arrival');},p.elevator.doorSpeed+.15);},p.player.animate?1.5:.15);},p.player.animate?1.2:.15);},p.elevator.doorSpeed+.1);}
 function answer(value){const q=p.tasks[s.floor],correct=checkAnswer(q,value);s=submit(p,s,value);sound(correct?'success':'error');feedback=correct?(q.onCorrect||p.rules.correct||t('correct')):(q.onWrong||p.rules.wrong||t('wrong'));render();if(['moving','descending'].includes(s.phase)){sound('travel');defer(()=>{sound('arrival');if(s.arrival==='win'){s.phase='win';render();focus();}else task();},p.elevator.speed);}else focus();}
 function selectObject(el){selection=el.dataset.select;el.focus({preventScroll:true});root.querySelectorAll('.chosen').forEach(x=>x.classList.remove('chosen'));el.classList.add('chosen');onSelect(selection);}
 function click(e){const b=e.target.closest('button,[data-select]');if(!b)return;if(editor){const el=b.closest('[data-select]');if(el)selectObject(el);return;}void audio.unlock();if(b.dataset.lift&&s.phase==='lobby'){board(b.dataset.lift);return;}
  if(b.dataset.floor&&['choose','ready'].includes(s.phase)){s.target=Number(b.dataset.floor);s.targetSelected=true;s.phase='ready';render();root.querySelector('.start-task')?.focus({preventScroll:true});return;}
  if(b.dataset.move){const[n,d]=b.dataset.move.split(',').map(Number);if(n+d>=0&&n+d<order.length){[order[n],order[n+d]]=[order[n+d],order[n]];render();root.querySelector(`[data-move="${n+d},${d}"]`)?.focus();}return;}
  const a=b.dataset.action;if(a==='begin'){s.phase='lobby';render();focus();}if(a==='go-back'&&['choose','ready'].includes(s.phase)){s.phase='lobby';s.targetSelected=false;render();focus();}if(a==='replay'){clearTimeout(transition);delete root.dataset.boardStep;s=initialGame(p);render();focus();}if(a==='ready'&&s.targetSelected)task();if(a==='sample'){sample=true;render();focus();}if(a==='oral-yes')answer(true);if(a==='oral-no')answer(false);if(a==='check'){const q=p.tasks[s.floor];if(['single','multiple'].includes(q.type)&&!selected.length)return;if(q.type==='text'&&!root.querySelector('#typed-answer').value.trim())return;answer(q.type==='order'?order:q.type==='text'?root.querySelector('#typed-answer').value:selected);}
 }
 const change=e=>{if(editor||e.target.name!=='answer')return;const n=Number(e.target.value);selected=p.tasks[s.floor].type==='single'?[n]:e.target.checked?[...selected,n]:selected.filter(x=>x!==n);root.querySelectorAll('.answer').forEach(el=>el.classList.toggle('selected',el.querySelector('input').checked));};
 const key=e=>{if(editor&&e.target.matches('[data-select]')){if(['Enter',' '].includes(e.key)){e.preventDefault();selectObject(e.target);}const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();const k=e.target.dataset.select,pos=p.layout[k],step=e.shiftKey?5:1;selection=k;onMove(k,Math.max(2,Math.min(98,pos.x+d[0]*step)),Math.max(2,Math.min(98,pos.y+d[1]*step)));root.querySelector(`[data-select="${k}"]`)?.focus();}return;}if(e.key==='Enter'&&e.target.id==='typed-answer'){e.preventDefault();root.querySelector('[data-action="check"]').click();}};
 let pointer=null;const down=e=>{if(!editor||e.button!==0)return;const el=e.target.closest('[data-select]');if(!el)return;selectObject(el);const r=root.getBoundingClientRect(),box=el.getBoundingClientRect(),pos=p.layout[el.dataset.select];pointer={id:e.pointerId,el,key:el.dataset.select,x:pos.x,y:pos.y,startX:e.clientX,startY:e.clientY,width:r.width,height:r.height,halfW:Math.min(49,box.width/r.width*50),halfH:Math.min(49,box.height/r.height*50),moved:false};root.setPointerCapture(e.pointerId);e.preventDefault();};
 const move=e=>{if(!pointer)return;const d=pointer,x=d.x+(e.clientX-d.startX)/d.width*100,y=d.y+(e.clientY-d.startY)/d.height*100;d.nextX=Math.max(d.halfW,Math.min(100-d.halfW,x));d.nextY=Math.max(d.halfH,Math.min(100-d.halfH,y));d.moved=Math.abs(e.clientX-d.startX)+Math.abs(e.clientY-d.startY)>3;d.el.style.setProperty('--x',d.nextX+'%');d.el.style.setProperty('--y',d.nextY+'%');};
 const up=e=>{if(!pointer)return;const d=pointer;pointer=null;if(root.hasPointerCapture(e.pointerId))root.releasePointerCapture(e.pointerId);if(d.moved)onMove(d.key,Math.round(d.nextX*10)/10,Math.round(d.nextY*10)/10);};const cancel=()=>{pointer=null;render();};
 let dragged=-1;const dragstart=e=>{if(editor){e.preventDefault();return;}dragged=Number(e.target.closest('[data-order]')?.dataset.order);e.dataTransfer?.setData('text/plain',String(dragged));},dragover=e=>{if(e.target.closest('[data-order]'))e.preventDefault();},drop=e=>{const target=e.target.closest('[data-order]');if(!target||editor)return;e.preventDefault();const n=Number(target.dataset.order);if(Number.isInteger(dragged)&&dragged>=0&&dragged<order.length){const[v]=order.splice(dragged,1);order.splice(n,0,v);render();}dragged=-1;};
 const handlers={click,change,keydown:key,pointerdown:down,pointermove:move,pointerup:up,pointercancel:cancel,dragstart,dragover,drop};for(const[name,fn]of Object.entries(handlers))root.addEventListener(name,fn);
 const timer=setInterval(()=>{if(editor||disposed)return;const old=s.phase;s=tick(p,s);if(old!==s.phase){clearTimeout(transition);render();focus();}else{const el=root.querySelector('[data-time]');if(el){el.textContent=time(s.remaining);el.closest('.timer').classList.toggle('warning',s.remaining<=p.rules.timer.warning);}}},1000);render();
 return {selectObject(key){selection=key;previewScreen='';render();},update(next){p=next;if(editor){previewScreen='';s=initialGame(p);render();}},setEditor(value){editor=value;clearTimeout(transition);delete root.dataset.boardStep;previewScreen='';s=initialGame(p);render();if(!editor)focus();},setView(value){view=value;previewScreen='';render();},showTask(index=0){if(editor&&p.tasks[index]){s.floor=index;selected=[];order=p.tasks[index].answers.map((_,i)=>i);sample=false;feedback='';previewScreen='task';render();}},showScreen(kind){if(editor){previewScreen=kind;render();}},playSound:kind=>audio.play(kind,{force:true}),destroy(){disposed=true;clearTimeout(transition);clearInterval(timer);audio.destroy();for(const[name,fn]of Object.entries(handlers))root.removeEventListener(name,fn);},state:()=>structuredClone(s)};
}
