import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
const hash=data=>createHash('sha256').update(data).digest('hex');
export async function verifyPlayers(root='players'){
 let names;try{names=await readdir(root);}catch(e){if(e.code==='ENOENT')return;throw e;}
 for(const name of names.filter(n=>/^v-[a-f0-9]{20}$/.test(n))){
  const dir=join(root,name),manifest=JSON.parse(await readFile(join(dir,'manifest.json'),'utf8'));
  if('v-'+hash(JSON.stringify(manifest.files)).slice(0,20)!==name||manifest.version!==name)throw Error('Invalid published player manifest: '+name);
  for(const [path,digest] of Object.entries(manifest.files))if(hash(await readFile(join(dir,path)))!==digest)throw Error('Published player was changed: '+name+'/'+path);
 }
 const legacy=names.includes('legacy.json')?JSON.parse(await readFile(join(root,'legacy.json'),'utf8')):null;
 if(legacy&&hash(await readFile('play.html'))!==legacy.bootstrapSHA256)throw Error('The legacy player address must stay pinned.');
}
export async function releasePlayer(){
 await verifyPlayers();
 const sources=['src/game/model.js','src/game/game.js','src/game/audio.js','src/game/lifts.js','src/game/math.js','src/game/player.js','src/storage/storage.js','src/storage/schema.js','src/styles/game.css','public/vendor/fflate.js','public/vendor/katex.min.js','public/vendor/katex-LICENSE.txt','public/favicon.svg',...(await readdir('src/locales')).filter(n=>n.endsWith('.json')).map(n=>'src/locales/'+n)];
 const files=new Map(await Promise.all(sources.map(async path=>[path,await readFile(path)])));
 files.set('play.html',await readFile('src/game/player-shell.html'));
 // The frozen reader has no import of the editor or the current release selector.
 const share=await readFile('src/export/share.js','utf8');
 files.set('src/export/share.js',Buffer.from("import {readProject} from '../storage/storage.js';\n"+share.slice(share.indexOf('export async function unpackShared'))));
 const entries=[...files].sort(([a],[b])=>a.localeCompare(b,'en'));
 const digests=Object.fromEntries(entries.map(([path,data])=>[path,hash(data)]));
 const version='v-'+hash(JSON.stringify(digests)).slice(0,20),dir='players/'+version;
 let exists=false;try{await readFile(dir+'/manifest.json');exists=true;}catch(e){if(e.code!=='ENOENT')throw e;}
 if(!exists){
  for(const [path,data] of entries){await mkdir(join(dir,path,'..'),{recursive:true});await writeFile(join(dir,path),data,{flag:'wx'});}
  await writeFile(dir+'/manifest.json',JSON.stringify({version,files:digests},null,2)+'\n',{flag:'wx'});
 }
 await writeFile('src/export/player-version.js',`// Generated by scripts/player-release.mjs. Published players are immutable.\nexport const PLAYER_VERSION='${version}';\n`);
 console.log('Pinned player: '+version);
 return version;
}
