import gifsicle from '../../public/vendor/gifsicle.js';
export const dataURL=blob=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob);});
export async function optimize(file,kind,p){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Выберите PNG, JPG, WebP или GIF');if(file.size>50*1024*1024)throw Error('Файл превышает 50 МБ');let blob=file;const max=kind==='background'?1920:kind==='task'?1000:1200;let warning='';
 if(file.type==='image/gif'){try{const output=await gifsicle.run({input:[{file,name:'input.gif'}],command:[`-O1 --resize-fit ${kind==='background'?1600:1200}x${kind==='background'?1600:1200} ${p.project.gifLossy?'--lossy='+p.project.gifLossy:''} input.gif -o /out/optimized.gif`]});if(output[0]?.size<file.size)blob=output[0];}catch{warning='Не удалось оптимизировать GIF. Сохранён оригинал с анимацией.';}}
 else if(typeof OffscreenCanvas!=='undefined'){blob=await new Promise((res,rej)=>{const w=new Worker(new URL('./image-worker.js',import.meta.url),{type:'module'});const timer=setTimeout(()=>{w.terminate();rej(Error('Обработка заняла слишком много времени'));},60000);w.onmessage=({data})=>{clearTimeout(timer);w.terminate();data.error?rej(Error(data.error)):res(data.blob);};w.onerror=()=>{clearTimeout(timer);w.terminate();rej(Error('Не удалось обработать изображение'));};w.postMessage({file,max,quality:p.project.quality,background:kind==='background'});});}
 else {const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);const result=await new Promise(res=>c.toBlob(res,'image/webp',p.project.quality));if(result&&(scale<1||result.size<file.size))blob=result;}finally{bitmap.close();}}
 if(blob.size>5*1024*1024)warning+=' Файл больше 5 МБ: загрузка в Genially может быть медленной.';
 return {id:'asset-'+crypto.randomUUID(),name:file.name,type:blob.type||file.type,data:await dataURL(blob),size:blob.size,original:file.size,warning};}
export function prune(p){const refs=new Set([p.theme.backgroundImage,p.player.media,p.rules.lifeMedia,...Object.values(p.screens).map(s=>s.media),...p.tasks.map(t=>t.media)]);p.assets=p.assets.filter(a=>refs.has(a.id));}
